### ISSUE TITLE
New ingredient is inserted a the wrong place

### ISSUE THREAD

**Issue by jgirardet** [codingforentrepreneurs/Try-Django-3.2#3]
Hi,
https://github.com/codingforentrepreneurs/Try-Django-3.2/blob/ee98140a5a014c45676284395f367a1379c33701/templates/recipes/create-update.html#L28

In level 68:
you add new ingredient before end of "ingredient-create", so at the end the new added ingredient is not in the same place as other ingredient :
```
ingredient1
ingredient2
div #ingredient-create > ingredient3
```
You could better add a div `#ingredientlist` around others ingredient and add the new ingredient beforeend of #ingredientlist to solve it.
 
PS: this tutorial is very very cool by the way

**Comment by teamcfe** [comment]
Great point! Submit a pull request! :)
