### ISSUE TITLE
Error: parsing app spec "deploy_on_push"

### ISSUE THREAD

**Issue by worksofindustry** [codingforentrepreneurs/Try-Django-3.2#5]
Running from a Windows 10 machine, doctl is saying "_deploy_on_push_" is an incorrect parameter in .do/app.yaml    

When running >  doctl apps create --spec .do/app.yaml --context main --format "ID"

My DigitalOcean API key is working, able to create/modify resources with it, my version of doctl is 1.64, and my configs in app.yaml

`databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: hello@teamcfe.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: cfe
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: vg*#tesrmi2bmtgit_t8)o6619mh+r$3y9zval%*r0k&u*tglp
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: password
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: password
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: password
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjango32
- key: OCR_API_TOKEN_HEADER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: password
- key: OCR_API_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: https://fastapi-microservice-for-django-d3kjd.ondigitalocean.app
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    branch: production-3
    deploy_on_push: true
    repo: worksofidustry/learn-django
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    branch: production-3
    deploy_on_push: true
    repo: worksofidustry/learn-django
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: try-django-3-2
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /
`

**Comment by codingforentrepreneurs** [comment]
Did you try to use the `app.yaml` from a pre-existing manually creation on the console?

**Comment by codingforentrepreneurs** [comment]
Also, be sure to use the correct formatting when pasting code. The button on GitHub is `<>`

**Comment by worksofindustry** [comment]
It was from the main of this repo .do/app.yaml. I've tried both running from Ananconda, and Git Bash, also replacing CRLF with LF just in case there is something Digital Ocean's API interface doesn't like.

**Comment by worksofindustry** [comment]
I may have something now by changing the param git, to github:   
```
  github:
    branch: production-3
    deploy_on_push: true....
```
